server {
    listen 5378;
    server_name 165.101.248.89;

    client_max_body_size 100M;

    # Frontend
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend Documentation
    location /docs {
        proxy_pass http://127.0.0.1:8002/docs;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /openapi.json {
        proxy_pass http://127.0.0.1:8002/openapi.json;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
    }

    # Static Media / Images
    location /digitaltwin-images/ {
        alias /opt/digitaltwin_images/;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        add_header Access-Control-Allow-Headers "*";

        types {
            model/gltf-binary glb;
        }
    }

    # Backend API
    location /api {
        proxy_pass http://127.0.0.1:8002/api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    location /api123 {
        proxy_pass https://novex.hpcl.co.in/api;
        proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host novex.hpcl.co.in;
        proxy_cache_bypass $http_upgrade;
    }

    error_page 502 /custom_502.html;
    location = /custom_502.html {
        root /usr/share/nginx/html;
        internal;
    }
}
